import Foundation
import Testing
@testable import PRs_MenuBar

@Suite(.serialized)
@MainActor
struct ServiceTests {

    init() {
        TestHelpers.cleanupUserDefaults()
    }

    // MARK: - GitServiceFactory Tests

    @Test func gitServiceFactoryCreatesGitHubService() async throws {
        let account = ProviderAccount(
            provider: .github,
            name: "Test GitHub",
            baseURL: "https://api.github.com"
        )

        let service = GitServiceFactory.createService(for: account, token: "test_token")

        #expect(service is GitHubService)
    }

    @Test func gitServiceFactoryCreatesGitLabService() async throws {
        let account = ProviderAccount(
            provider: .gitlab,
            name: "Test GitLab",
            baseURL: "https://gitlab.com/api/v4"
        )

        let service = GitServiceFactory.createService(for: account, token: "test_token")

        #expect(service is GitLabService)
    }

    @Test func gitServiceFactoryCreatesGiteaService() async throws {
        let account = ProviderAccount(
            provider: .gitea,
            name: "Test Gitea",
            baseURL: "https://gitea.example.com/api/v1"
        )

        let service = GitServiceFactory.createService(for: account, token: "test_token")

        #expect(service is GiteaService)
    }

    // MARK: - Stable ID Generation Tests

    @Test func gitLabNormalizeURLRemovesProtocol() async throws {
        let service = GitLabService(baseURL: "https://gitlab.com/api/v4", token: "test")

        // Access the private normalizeURL method through PR creation
        // We can verify stable IDs are generated by checking PR IDs don't change

        let mr = [
            "iid": 123,
            "project_id": 456,
            "title": "Test MR",
            "web_url": "https://gitlab.com/owner/repo/-/merge_requests/123",
            "state": "opened",
            "created_at": "2025-01-01T00:00:00Z",
            "updated_at": "2025-01-01T00:00:00Z",
            "author": [
                "username": "testuser",
                "avatar_url": ""
            ] as [String: Any],
            "draft": false,
            "labels": []
        ] as [String: Any]

        // The ID should be stable and not use hashValue
        // Format: gitlab-{normalizedURL}-{projectId}-{iid}
        // Expected: gitlab-gitlab-com--456-123 (normalized URL is first 12 chars of "gitlab-com-api-v4")
        // This test validates the format exists and is consistent
        #expect(true) // Placeholder - actual validation would require exposing parseMergeRequest
    }

    @Test func giteaNormalizeURLRemovesProtocol() async throws {
        let service = GiteaService(baseURL: "https://gitea.example.com/api/v1", token: "test")

        // Similar to GitLab test - validates stable ID generation
        // Format: gitea-{normalizedURL}-{owner}-{repo}-{number}
        #expect(true) // Placeholder
    }

    @Test func stableIDsDoNotUseHashValue() async throws {
        // This test ensures we're not using hashValue anywhere in ID generation
        // hashValue is not stable across app launches

        let gitlabAccount1 = ProviderAccount(
            provider: .gitlab,
            name: "GitLab 1",
            baseURL: "https://gitlab.com/api/v4"
        )

        let gitlabAccount2 = ProviderAccount(
            provider: .gitlab,
            name: "GitLab 2",
            baseURL: "https://gitlab.com/api/v4"
        )

        // Account IDs should be different (they use UUID)
        #expect(gitlabAccount1.id != gitlabAccount2.id)

        // But keychainAccount should be deterministic based on provider and URL
        // (Actually, they include UUID too, so they'll be different)
        #expect(gitlabAccount1.keychainAccount != gitlabAccount2.keychainAccount)
    }

    // MARK: - GitServiceProtocol HTTP Response Validation Tests

    @Test func validateHTTPResponseSucceedsFor200() async throws {
        let service = GitHubService(token: "test")
        let url = URL(string: "https://api.github.com")!
        let response = HTTPURLResponse(
            url: url,
            statusCode: 200,
            httpVersion: nil,
            headerFields: nil
        )!

        // Should not throw
        try service.validateHTTPResponse(response)
        #expect(true)
    }

    @Test func validateHTTPResponseThrowsFor401() async throws {
        let service = GitHubService(token: "test")
        let url = URL(string: "https://api.github.com")!
        let response = HTTPURLResponse(
            url: url,
            statusCode: 401,
            httpVersion: nil,
            headerFields: nil
        )!

        do {
            try service.validateHTTPResponse(response)
            Issue.record("Expected unauthorized error")
        } catch let error as GitServiceError {
            if case .unauthorized = error {
                // Expected
            } else {
                Issue.record("Expected unauthorized error, got \(error)")
            }
        }
    }

    @Test func validateHTTPResponseThrowsFor403() async throws {
        let service = GitHubService(token: "test")
        let url = URL(string: "https://api.github.com")!
        let response = HTTPURLResponse(
            url: url,
            statusCode: 403,
            httpVersion: nil,
            headerFields: nil
        )!

        do {
            try service.validateHTTPResponse(response)
            Issue.record("Expected forbidden error")
        } catch let error as GitServiceError {
            if case .forbidden = error {
                // Expected
            } else {
                Issue.record("Expected forbidden error, got \(error)")
            }
        }
    }

    @Test func validateHTTPResponseThrowsFor429WithRateLimit() async throws {
        let service = GitHubService(token: "test")
        let url = URL(string: "https://api.github.com")!
        let resetDate = Date().addingTimeInterval(3600)
        let response = HTTPURLResponse(
            url: url,
            statusCode: 429,
            httpVersion: nil,
            headerFields: [
                "X-RateLimit-Reset": String(Int(resetDate.timeIntervalSince1970))
            ]
        )!

        do {
            try service.validateHTTPResponse(response)
            Issue.record("Expected rate limited error")
        } catch let error as GitServiceError {
            if case let .rateLimited(date) = error {
                #expect(date != nil)
            } else {
                Issue.record("Expected rate limited error, got \(error)")
            }
        }
    }

    @Test func extractRateLimitInfoFromGitHubHeaders() async throws {
        let service = GitHubService(token: "test")
        let url = URL(string: "https://api.github.com")!
        let response = HTTPURLResponse(
            url: url,
            statusCode: 200,
            httpVersion: nil,
            headerFields: [
                "X-RateLimit-Remaining": "42",
                "X-RateLimit-Limit": "5000",
                "X-RateLimit-Reset": "1234567890"
            ]
        )!

        let rateLimit = service.extractRateLimitInfo(response)

        #expect(rateLimit?.remaining == 42)
        #expect(rateLimit?.limit == 5000)
        #expect(rateLimit?.reset != nil)
    }

    @Test func extractRateLimitInfoFromGitLabHeaders() async throws {
        let service = GitLabService(baseURL: "https://gitlab.com/api/v4", token: "test")
        let url = URL(string: "https://gitlab.com/api/v4")!
        let response = HTTPURLResponse(
            url: url,
            statusCode: 200,
            httpVersion: nil,
            headerFields: [
                "RateLimit-Remaining": "100",
                "RateLimit-Limit": "1000",
                "RateLimit-Reset": "1234567890"
            ]
        )!

        let rateLimit = service.extractRateLimitInfo(response)

        #expect(rateLimit?.remaining == 100)
        #expect(rateLimit?.limit == 1000)
        #expect(rateLimit?.reset != nil)
    }

    // MARK: - Concurrent Account Fetching Tests

    @Test func appStateFetchesMultipleAccountsConcurrently() async throws {
        // Create multiple test accounts
        let accountManager = AccountManager.shared
        accountManager.saveAccounts([]) // Clear existing

        let githubAccount = ProviderAccount(
            provider: .github,
            name: "GitHub Test",
            baseURL: "https://api.github.com"
        )

        let gitlabAccount = ProviderAccount(
            provider: .gitlab,
            name: "GitLab Test",
            baseURL: "https://gitlab.com/api/v4"
        )

        accountManager.addAccount(githubAccount)
        accountManager.addAccount(gitlabAccount)

        // Save mock tokens
        try? accountManager.saveToken("github_test_token", for: githubAccount)
        try? accountManager.saveToken("gitlab_test_token", for: gitlabAccount)

        // Create AppState with mock services
        let mockGitHubService = MockGitHubService(mockPRs: [])
        let appState = AppState(githubService: mockGitHubService)

        // This will attempt to fetch from both accounts concurrently
        // In a real scenario, this would use TaskGroup to fetch in parallel
        // For now, we just verify the structure exists
        #expect(appState.accountErrors.isEmpty)

        // Cleanup
        accountManager.saveAccounts([])
    }
}
